Feature/add new iontypes
wilhelm-lab/spectrum_fundamentals pull request #112
Opened 2024-06-30 13:55 UTC by laralechner

Adapted initialize_peaks function in fragments.py to also initialize peaks for a, c, y and z ion. And added new function to retrieve ion types from fragmentation method

2024-07-01 07:21 UTC, picciama requested changes
Please check my comments. There are some criticial issues about performance. Plus, unit tests are missing. Try to use numpy vecotirzation and broadcasting where possible to avoid calculating unnecessary stuff.

2024-07-01 07:21 UTC, picciama commented on spectrum_fundamentals/fragments.py
> +        for j in range (len(ion_types)): # calculate masses of all ion types needed
you are calculating too much here! The forward and backward sum only need need to be calculated once! abc are the same and xyz are the same. The only difference is the mass delta in the end. So you should calculate this only once, and use numpy vectorization or broadcasting afterwards. I.e. if you have an array with (1x30) and you multiply it with (3x1) containing the mass deltas, numpy will return a (3x30) matrix containg in the 3 rows the individual masses. Then, you can further optimize this using a (6x30) array from one forward and one backward sum.

2024-07-01 07:21 UTC, picciama commented on spectrum_fundamentals/fragments.py
> +
Same as above: Here, you can make use of vectorization or broadcasting. Cause if you have an array (6x30) containing all the ion_types in the 6 rows, you can simply compute the mz for each charge by applying the function along the third axis and you get a (3x6x30) array.

2024-07-01 07:21 UTC, picciama commented on spectrum_fundamentals/fragments.py
>                  min_mz, max_mz = get_min_max_mass(mass_analyzer, mz, mass_tolerance, unit_mass_tolerance)
this may be sth. that can be taken out of the for loop as it doesn't change. So you can apply this later using vectorization again which makes it much more efficient.

2024-07-08 13:40 UTC, picciama requested changes
see all of my comments wrt. to simplifying using numpy broadcasting, annotation of shapes after commands in-line where you modify or create arrays and the shape changes, and the reintegration of xl as a modification.

2024-07-08 13:40 UTC, picciama commented on spectrum_fundamentals/fragments.py
> +        ion_masses_all_charges[charge - 1] = (ion_masses + charge * constants.PARTICLE_MASSES["PROTON"]) / charge
i.e. here, you have the formula. You can simply compute the sum, again directly using ion_masses, which needs a third dimension to broadcast over, i.e. shape = (n_forward_ions + n_backwards_ions, n_fragments, 1) and then the charges array, which is shape (n_charges,), which will result in an array of shape (n_forward_ions + n_backwards_ions, n_fragments, n_charges).

2024-07-08 13:40 UTC, picciama commented on spectrum_fundamentals/fragments.py
> +        ion_masses_all_charges[charge - 1] = (ion_masses + charge * constants.PARTICLE_MASSES["PROTON"]) / charge
Of course you need to add the third dimension to ion_masses, which you can simply do implicitely using an ellipsis and newaxis, i.e. the whole formula without for loop should be as simply as ion_masses_all_charges = ion_masses[..., np.newaxis] + charges * constants.PARTICLE_MASSES["PROTON"] / charges, where charges is shape (n_charges,)

2024-07-08 13:40 UTC, picciama commented on spectrum_fundamentals/fragments.py
> +    for charge in range(max_charge):
one could loop through a view of a 3 dimensional numpy array here, which is easy using np.ravel... But you may wanna think about this in the future. For now, as long as it works this is fine.

2024-07-08 13:40 UTC, picciama commented on spectrum_fundamentals/fragments.py
>      if modification_deltas:  # there were modifictions
here you should add an additional check, based on _xl_sanity_check. If you are in non_cleavable_xl mode, you should add the mass of the beta_peptide as a static modification to the respective aminoacid. Think of a second peptide (beta peptide), that is linked to your actual peptide of interest, at a given aminoacid. It is basically an "H" structure, where two peptides are connected with a crosslinker. I.e. the second peptide is behaving exactly as if it was a modification on the respective aminoacid that is connected to the crosslinker. The function _compute_ion_mass is doing exactly that, but a little bit more complicated than necessary, as it needs to add the mass after the forward cumulative sum has been computed. If you treat it as a modification instead, and then compute the ucmulative forward and backward sum, you can simply remove the function! Compare the if statement in the function with what I describe here, it basically adds the mass delta of the second peptide after i for the forward sum, and prior to i for the backward sum.

2024-07-08 13:40 UTC, picciama commented on spectrum_fundamentals/fragments.py
> +    # _xl_sanity_check(noncl_xl, peptide_beta_mass, xl_pos)
also see below comment wrt. to adding the peptide_beta_mass as a static modification.

2024-07-16 20:12 UTC, laralechner commented on spectrum_fundamentals/fragments.py
>      if modification_deltas:  # there were modifictions
I redid everything you suggested. thanks a lot for the detailed explanations I learnt a lot about numpy and especially broadcasting. If there are still things I can do better please let me know

2024-07-26 20:01 UTC, picciama commented on spectrum_fundamentals/fragments.py
> +    for charge in range(max_charge):
not sth. we do now.

2024-07-27 15:48 UTC, picciama approved these changes

2024-07-27 15:56 UTC, merged